### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hyewon-Yang** [tsleng93/SocialBubble#2]
There seems to be an error in PruneMatrixFull.m file when I try to run your code.
Matlab says there is no value in NewM.
Please check it!

**Comment by tsleng93** [comment]
Thanks for flagging this, the last line of the code had been omitted in error, simply assigning NewM = M.

This has now been updated,
Trystan

**Comment by Hyewon-Yang** [comment]
Thank you for quick response. I'm really interested in your research. Good luck to you!
